name: Validate Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited
      - reopened
    branches:    
      - 'main'
      - 'release-**'
      - 'develop'
  
jobs:
  validate-PR-issue:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      env:
        MY_TOKEN: ${{ secrets.MY_TOKEN }}
      run: |
        echo "$MY_TOKEN" | gh auth login --with-token
        gh pr comment 1 --body "demo 1"
